using LinearAlgebra: diag, norm
using SparseArrays

"""
    tensor_quad_nodes(p::Int; operator_type::String = "lgl", n1d::Int = -1)

Compute tensor-product nodes on the reference quadrilateral from the selected
one-dimensional SBP operator.

Returns `(xy, w)`, where `xy` contains the tensor-product node coordinates and `w`
contains the one-dimensional quadrature weights.
"""
function tensor_quad_nodes(p::Int; operator_type::String = "lgl", n1d::Int = -1)
    if operator_type == "lgl"
        # Degree p LGL operators use degree 2p - 1 quadrature
        q, w = quadrature(Line(), GaussLobattoQuadrature(p, 0, 0))
    elseif operator_type == "opt"
        (~, ~, H, q) = get_1d_opt(p)
        w = diag(H)
    elseif operator_type == "optimal"
        (~, ~, H, q) = get_1d_optimal(p)
        w = diag(H)
    elseif operator_type == "minimal"
        (~, ~, H, q) = get_1d_minimal(p)
        w = diag(H)
    elseif operator_type == "csbp"
        (~, ~, H, q) = get_1d_csbp(p)
        w = diag(H)
    else
        error("Operator not implemented. Must be 'lgl, 'opt', or 'csbp'.")
    end
    Q = length(q)
    x = repeat(q, Q)
    y = repeat(q, inner = Q)
    xy = [x'; y']
    return xy, w
end

"""
    tensor_hex_nodes(p::Int; operator_type::String = "lgl", n1d::Int = -1)

Compute tensor-product nodes on the reference hexahedron from the selected
one-dimensional SBP operator.

Returns `(xyz, w)`, where `xyz` contains the tensor-product node coordinates and `w`
contains the one-dimensional quadrature weights.
"""
function tensor_hex_nodes(p::Int; operator_type::String = "lgl", n1d::Int = -1)
    if operator_type == "lgl"
        q, w = quadrature(Line(), GaussLobattoQuadrature(p, 0, 0))
    elseif operator_type == "opt"
        (~, ~, H, q) = get_1d_opt(p)
        w = diag(H)
    elseif operator_type == "optimal"
        (~, ~, H, q) = get_1d_optimal(p)
        w = diag(H)
    elseif operator_type == "minimal"
        (~, ~, H, q) = get_1d_minimal(p)
        w = diag(H)
    elseif operator_type == "csbp"
        (~, ~, H, q) = get_1d_csbp(p)
        w = diag(H)
    else
        error("Operator not implemented. Must be 'lgl or 'opt'.")
    end
    Q = length(q)

    x = repeat(q, Q * Q)
    y = repeat(repeat(q, inner = Q), outer = Q)
    z = repeat(q, inner = Q^2)

    xyz = [x'; y'; z']

    return xyz, w
end

"""
    square_quad_map(xp::Array{T}, quad_vert::Array{T}) where {T}

Map a point from the reference square `[-1, 1]^2` to the quadrilateral with vertices
`quad_vert`.

Returns the mapped physical coordinate.
"""
function square_quad_map(xp::Array{T}, quad_vert::Array{T}) where {T}
    xi = xp[1]
    eta = xp[2]
    psi = []
    push!(psi, 1 / 4 * (1 - xi) * (1 - eta))
    push!(psi, 1 / 4 * (1 + xi) * (1 - eta))
    push!(psi, 1 / 4 * (1 - xi) * (1 + eta))
    push!(psi, 1 / 4 * (1 + xi) * (1 + eta))

    x = zeros(2, 1)
    for i in 1:2
        for j in 1:4
            x[i] += quad_vert[j, i] * psi[j]
        end
    end
    return x
end

"""
    cube_hex_map(xp::Array{T}, hex_vert::Array{T}) where {T}

Map a point from the reference cube `[-1, 1]^3` to the hexahedron with vertices
`hex_vert`.

Returns the mapped physical coordinate.
"""
function cube_hex_map(xp::Array{T}, hex_vert::Array{T}) where {T}
    xi = xp[1]
    eta = xp[2]
    zeta = xp[3]
    psi = []

    push!(psi, 1 / 8 * (1 - xi) * (1 - eta) * (1 - zeta))
    push!(psi, 1 / 8 * (1 + xi) * (1 - eta) * (1 - zeta))
    push!(psi, 1 / 8 * (1 - xi) * (1 + eta) * (1 - zeta))
    push!(psi, 1 / 8 * (1 + xi) * (1 + eta) * (1 - zeta))
    push!(psi, 1 / 8 * (1 - xi) * (1 - eta) * (1 + zeta))
    push!(psi, 1 / 8 * (1 + xi) * (1 - eta) * (1 + zeta))
    push!(psi, 1 / 8 * (1 - xi) * (1 + eta) * (1 + zeta))
    push!(psi, 1 / 8 * (1 + xi) * (1 + eta) * (1 + zeta))

    x = zeros(3, 1)
    for i in 1:3
        for j in 1:8
            x[i] += hex_vert[j, i] * psi[j]
        end
    end

    return x
end

"""
    square_to_tri_map(xi::Array{T}) where {T}

Map reference-square points to the three quadrilaterals generated by splitting the
reference triangle.

Returns the coordinates of all mapped split-triangle points.
"""
function square_to_tri_map(xi::Array{T}) where {T}
    quad_vert = get_quad_vert()
    n = size(xi, 2)
    x = zeros(2, 3 * n)
    for i in 0:2
        for j in 1:n
            xp = square_quad_map(xi[:, j], quad_vert[i + 1])
            x[:, i * n + j] = xp
        end
    end
    return x
end

"""
    get_quad_vert()

Return the vertices of the three quadrilaterals obtained by splitting the reference
triangle with vertices `[-1 -1; 1 -1; -1 1]`.
"""
function get_quad_vert()
    quad_vert = [[-1 -1; 0 -1; -1 0; -1/3 -1/3],
        [0 -1; 1 -1; -1/3 -1/3; 0 0],
        [-1 0; -1/3 -1/3; -1 1; 0 0]]
    return quad_vert
end

"""
    get_hex_vert(; T = Float64)

Return the vertices of the four hexahedra obtained by splitting the reference
tetrahedron with vertices `[-1 -1 -1; 1 -1 -1; -1 1 -1; -1 -1 1]`.
"""
function get_hex_vert(; T = Float64)
    v1 = T[-1 -1 -1]
    v2 = T[1 -1 -1]
    v3 = T[-1 1 -1]
    v4 = T[-1 -1 1]
    v5 = T[0 0 -1]
    v6 = T[-1 0 -1]
    v7 = T[0 -1 -1]
    v8 = T[-1 0 0]
    v9 = T[-1 -1 0]
    v10 = T[0 -1 0]
    v11 = T[-1 / 3 -1 / 3 -1]
    v12 = T[-1 / 3 -1 / 3 -1 / 3]
    v13 = T[-1 -1 / 3 -1 / 3]
    v14 = T[-1 / 3 -1 -1 / 3]
    v15 = T[-1 / 2 -1 / 2 -1 / 2]
    hex_vert = [[v2; v5; v7; v11; v10; v12; v14; v15],
        [v5; v3; v11; v6; v12; v8; v15; v13],
        [v7; v11; v1; v6; v14; v15; v9; v13],
        [v10; v4; v12; v8; v14; v9; v15; v13]]
    return hex_vert
end

"""
    cube_to_tet_map(xi::Array{T}) where {T}

Map reference-cube points to the four hexahedra generated by splitting the reference
tetrahedron.

Returns the coordinates of all mapped split-tetrahedron points.
"""
function cube_to_tet_map(xi::Array{T}) where {T}
    hex_vert = get_hex_vert()
    n = size(xi, 2)
    x = zeros(3, 4 * n)
    for i in 0:3
        for j in 1:n
            xp = cube_hex_map(xi[:, j], Matrix(hex_vert[i + 1]))
            x[:, i * n + j] = xp
        end
    end
    return x
end

"""
    metric_tri!(xp::Array{T}, quad_vert::Array{T}, dxi::SubArray{T},
                dx::SubArray{T}, Jac::SubArray{T}) where {T}

Compute metric terms for a point mapped from the reference square to a quadrilateral
in the split triangle.

The arrays `dxi`, `dx`, and `Jac` are overwritten in place with the forward metrics,
inverse metrics, and metric Jacobian.
"""
function metric_tri!(xp::Array{T}, quad_vert::Array{T}, dxi::SubArray{T},
        dx::SubArray{T}, Jac::SubArray{T}) where {T}
    ξ = xp[1]
    η = xp[2]

    ∂Ψ∂ξ = []
    ∂Ψ∂η = []
    push!(∂Ψ∂ξ, -1 / 4 * (1 - η))
    push!(∂Ψ∂ξ, 1 / 4 * (1 - η))
    push!(∂Ψ∂ξ, -1 / 4 * (1 + η))
    push!(∂Ψ∂ξ, 1 / 4 * (1 + η))

    push!(∂Ψ∂η, -1 / 4 * (1 - ξ))
    push!(∂Ψ∂η, -1 / 4 * (1 + ξ))
    push!(∂Ψ∂η, 1 / 4 * (1 - ξ))
    push!(∂Ψ∂η, 1 / 4 * (1 + ξ))

    ∂x∂ξ = 0.0
    ∂x∂η = 0.0
    ∂y∂ξ = 0.0
    ∂y∂η = 0.0

    for j in 1:4
        ∂x∂ξ += quad_vert[j, 1] * ∂Ψ∂ξ[j]
        ∂x∂η += quad_vert[j, 1] * ∂Ψ∂η[j]
        ∂y∂ξ += quad_vert[j, 2] * ∂Ψ∂ξ[j]
        ∂y∂η += quad_vert[j, 2] * ∂Ψ∂η[j]
    end

    J = ∂x∂ξ * ∂y∂η - ∂x∂η * ∂y∂ξ
    ∂ξ∂x = ∂y∂η / J
    ∂ξ∂y = -∂x∂η / J
    ∂η∂x = -∂y∂ξ / J
    ∂η∂y = ∂x∂ξ / J

    Jac[1, 1] = J
    dxi[1, 1] = ∂x∂ξ
    dxi[2, 1] = ∂x∂η
    dxi[3, 1] = ∂y∂ξ
    dxi[4, 1] = ∂y∂η

    dx[1, 1] = ∂ξ∂x
    dx[2, 1] = ∂ξ∂y
    dx[3, 1] = ∂η∂x
    dx[4, 1] = ∂η∂y
end

"""
    metric_tet!(xp::Array{T}, hex_vert::Array{T}, dxi::SubArray{T},
                dx::SubArray{T}, Jac::SubArray{T}) where {T}

Compute metric terms for a point mapped from the reference cube to a hexahedron in
the split tetrahedron.

The arrays `dxi`, `dx`, and `Jac` are overwritten in place with the forward metrics,
inverse metrics, and metric Jacobian.
"""
function metric_tet!(xp::Array{T}, hex_vert::Array{T}, dxi::SubArray{T},
        dx::SubArray{T}, Jac::SubArray{T}) where {T}
    ξ = xp[1]
    η = xp[2]
    ζ = xp[3]
    ∂Ψ∂ξ = []
    ∂Ψ∂η = []
    ∂Ψ∂ζ = []

    push!(∂Ψ∂ξ, -1 / 8 * (1 - η) * (1 - ζ))
    push!(∂Ψ∂ξ, 1 / 8 * (1 - η) * (1 - ζ))
    push!(∂Ψ∂ξ, -1 / 8 * (1 + η) * (1 - ζ))
    push!(∂Ψ∂ξ, 1 / 8 * (1 + η) * (1 - ζ))
    push!(∂Ψ∂ξ, -1 / 8 * (1 - η) * (1 + ζ))
    push!(∂Ψ∂ξ, 1 / 8 * (1 - η) * (1 + ζ))
    push!(∂Ψ∂ξ, -1 / 8 * (1 + η) * (1 + ζ))
    push!(∂Ψ∂ξ, 1 / 8 * (1 + η) * (1 + ζ))

    push!(∂Ψ∂η, -1 / 8 * (1 - ξ) * (1 - ζ))
    push!(∂Ψ∂η, -1 / 8 * (1 + ξ) * (1 - ζ))
    push!(∂Ψ∂η, 1 / 8 * (1 - ξ) * (1 - ζ))
    push!(∂Ψ∂η, 1 / 8 * (1 + ξ) * (1 - ζ))
    push!(∂Ψ∂η, -1 / 8 * (1 - ξ) * (1 + ζ))
    push!(∂Ψ∂η, -1 / 8 * (1 + ξ) * (1 + ζ))
    push!(∂Ψ∂η, 1 / 8 * (1 - ξ) * (1 + ζ))
    push!(∂Ψ∂η, 1 / 8 * (1 + ξ) * (1 + ζ))

    push!(∂Ψ∂ζ, -1 / 8 * (1 - ξ) * (1 - η))
    push!(∂Ψ∂ζ, -1 / 8 * (1 + ξ) * (1 - η))
    push!(∂Ψ∂ζ, -1 / 8 * (1 - ξ) * (1 + η))
    push!(∂Ψ∂ζ, -1 / 8 * (1 + ξ) * (1 + η))
    push!(∂Ψ∂ζ, 1 / 8 * (1 - ξ) * (1 - η))
    push!(∂Ψ∂ζ, 1 / 8 * (1 + ξ) * (1 - η))
    push!(∂Ψ∂ζ, 1 / 8 * (1 - ξ) * (1 + η))
    push!(∂Ψ∂ζ, 1 / 8 * (1 + ξ) * (1 + η))

    ∂x∂ξ = 0.0
    ∂x∂η = 0.0
    ∂x∂ζ = 0.0
    ∂y∂ξ = 0.0
    ∂y∂η = 0.0
    ∂y∂ζ = 0.0
    ∂z∂ξ = 0.0
    ∂z∂η = 0.0
    ∂z∂ζ = 0.0

    for j in 1:8
        ∂x∂ξ += hex_vert[j, 1] * ∂Ψ∂ξ[j]
        ∂x∂η += hex_vert[j, 1] * ∂Ψ∂η[j]
        ∂x∂ζ += hex_vert[j, 1] * ∂Ψ∂ζ[j]

        ∂y∂ξ += hex_vert[j, 2] * ∂Ψ∂ξ[j]
        ∂y∂η += hex_vert[j, 2] * ∂Ψ∂η[j]
        ∂y∂ζ += hex_vert[j, 2] * ∂Ψ∂ζ[j]

        ∂z∂ξ += hex_vert[j, 3] * ∂Ψ∂ξ[j]
        ∂z∂η += hex_vert[j, 3] * ∂Ψ∂η[j]
        ∂z∂ζ += hex_vert[j, 3] * ∂Ψ∂ζ[j]
    end

    J = (∂x∂ξ * ∂y∂η * ∂z∂ζ +
         ∂x∂η * ∂y∂ζ * ∂z∂ξ +
         ∂x∂ζ * ∂y∂ξ * ∂z∂η -
         ∂x∂ζ * ∂y∂η * ∂z∂ξ -
         ∂x∂η * ∂y∂ξ * ∂z∂ζ -
         ∂x∂ξ * ∂y∂ζ * ∂z∂η)

    ∂ξ∂x = 1 / J * (∂y∂η * ∂z∂ζ - ∂y∂ζ * ∂z∂η)
    ∂η∂x = 1 / J * (∂y∂ζ * ∂z∂ξ - ∂y∂ξ * ∂z∂ζ)
    ∂ζ∂x = 1 / J * (∂y∂ξ * ∂z∂η - ∂y∂η * ∂z∂ξ)

    ∂ξ∂y = 1 / J * (∂x∂ζ * ∂z∂η - ∂x∂η * ∂z∂ζ)
    ∂η∂y = 1 / J * (∂x∂ξ * ∂z∂ζ - ∂x∂ζ * ∂z∂ξ)
    ∂ζ∂y = 1 / J * (∂x∂η * ∂z∂ξ - ∂x∂ξ * ∂z∂η)

    ∂ξ∂z = 1 / J * (∂x∂η * ∂y∂ζ - ∂x∂ζ * ∂y∂η)
    ∂η∂z = 1 / J * (∂x∂ζ * ∂y∂ξ - ∂x∂ξ * ∂y∂ζ)
    ∂ζ∂z = 1 / J * (∂x∂ξ * ∂y∂η - ∂x∂η * ∂y∂ξ)

    Jac[1, 1] = J
    dxi[1, 1] = ∂x∂ξ
    dxi[2, 1] = ∂x∂η
    dxi[3, 1] = ∂x∂ζ
    dxi[4, 1] = ∂y∂ξ
    dxi[5, 1] = ∂y∂η
    dxi[6, 1] = ∂y∂ζ
    dxi[7, 1] = ∂z∂ξ
    dxi[8, 1] = ∂z∂η
    dxi[9, 1] = ∂z∂ζ

    dx[1, 1] = ∂ξ∂x
    dx[2, 1] = ∂ξ∂y
    dx[3, 1] = ∂ξ∂z
    dx[4, 1] = ∂η∂x
    dx[5, 1] = ∂η∂y
    dx[6, 1] = ∂η∂z
    dx[7, 1] = ∂ζ∂x
    dx[8, 1] = ∂ζ∂y
    dx[9, 1] = ∂ζ∂z
end

"""
    tensor_operators(p::Int, dim::Int; operator_type::String = "lgl",
                     n1d::Int = -1, T = Float64)

Construct tensor-product SBP operators in `dim` dimensions from a one-dimensional SBP
operator.

Returns `(H, Q, D, E, R)`, where `H` is the norm matrix, `Q` is the SBP flux
differencing matrix, `D` is the differentiation matrix, `E` is the boundary
integration matrix, and `R` extrapolates volume values to facets.
"""
function tensor_operators(
        p::Int, dim::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    if operator_type == "lgl"
        LGL_quadrature = LGLQuadrature(p)
        _, w = quadrature(Line(), LGL_quadrature)
        _, _, _, D1, _, _, _ = operators_1d(LGL_quadrature)
        D1 = Matrix(D1)
        H1 = Diagonal(w)
        Q1 = H1 * D1
        E1 = Q1 + Q1'
        n = length(w)
    elseif operator_type == "opt"
        (D1, Q1, H1, ~) = get_1d_opt(p)
        E1 = Q1 + Q1'
        n = size(H1, 1)
    elseif operator_type == "optimal"
        (D1, Q1, H1, ~) = get_1d_optimal(p)
        E1 = Q1 + Q1'
        n = size(H1, 1)
    elseif operator_type == "minimal"
        (D1, Q1, H1, ~) = get_1d_minimal(p)
        E1 = Q1 + Q1'
        n = size(H1, 1)
    elseif operator_type == "csbp"
        (D1, Q1, H1, ~) = get_1d_csbp(p)
        E1 = Q1 + Q1'
        n = size(H1, 1)
    else
        error("Operator not implemented. Must be 'lgl, 'opt', or 'csbp'.")
    end
    In = I(n)
    tR = zeros(T, (n, 1))
    tR[end] = 1.0
    tL = zeros(T, (n, 1))
    tL[1] = 1.0

    H = zeros(T, (n^dim, n^dim))
    Q = zeros(T, (n^dim, n^dim, dim))
    D = zeros(T, (n^dim, n^dim, dim))
    E = zeros(T, (n^dim, n^dim, dim))
    R = zeros(T, (n^(dim - 1), n^dim, 2 * dim))

    if dim == 2
        H[:, :] = kron(H1, H1)
        Q[:, :, 1] = kron(H1, Q1)
        Q[:, :, 2] = kron(Q1, H1)
        D[:, :, 1] = kron(In, D1)
        D[:, :, 2] = kron(D1, In)
        E[:, :, 1] = kron(In, E1)
        E[:, :, 2] = kron(E1, In)
        R[:, :, 1] = kron(In, tL') #left facet (x=-1)
        R[:, :, 2] = kron(In, tR') #right facet (x=1)
        R[:, :, 3] = kron(tL', In) #bottom facet (y=-1)
        R[:, :, 4] = kron(tR', In) #top facet (y=1)
    elseif dim == 3
        H[:, :] = kron(H1, kron(H1, H1))
        Q[:, :, 1] = kron(H1, kron(H1, Q1))
        Q[:, :, 2] = kron(H1, kron(Q1, H1))
        Q[:, :, 3] = kron(Q1, kron(H1, H1))
        D[:, :, 1] = kron(In, kron(In, D1))
        D[:, :, 2] = kron(In, kron(D1, In))
        D[:, :, 3] = kron(D1, kron(In, In))
        E[:, :, 1] = kron(In, kron(In, E1))
        E[:, :, 2] = kron(In, kron(E1, In))
        E[:, :, 3] = kron(E1, kron(In, In))
        R[:, :, 1] = kron(In, kron(In, tL')) #left facet (x=-1)
        R[:, :, 2] = kron(In, kron(In, tR')) #right facet (x=1)
        R[:, :, 3] = kron(In, kron(tL', In)) #back facet (y=-1)
        R[:, :, 4] = kron(In, kron(tR', In)) #front facet (y=1)
        R[:, :, 5] = kron(tL', kron(In, In)) #bottom facet (z=-1)
        R[:, :, 6] = kron(tR', kron(In, In)) #top facet (z=1)
    end
    return H, Q, D, E, R
end

"""
    normals_square(nf::Int; T = Float64)

Return the outward unit normals at the facet nodes of the reference square
`[-1, 1]^2`.
"""
function normals_square(nf::Int; T = Float64)
    dim = 2
    N = zeros(T, (dim, nf, 4)) # normal vector for each facet

    N[1, :, 1] .= -1.0
    N[1, :, 2] .= 1.0
    N[2, :, 3] .= -1.0
    N[2, :, 4] .= 1.0

    return N
end

"""
    facet_nodes_square(n::Int)

Return the element node indices associated with each facet of a square element with
`n` nodes.
"""
function facet_nodes_square(n::Int)
    nf = convert(Int, sqrt(n))
    facet_node_idx = zeros(Int, (4, nf))

    facet_node_idx[1, :] = 1:nf:n
    facet_node_idx[2, :] = nf:nf:n
    facet_node_idx[3, :] = 1:nf
    facet_node_idx[4, :] = (n + 1 - nf):n

    return facet_node_idx
end

"""
    normals_cube(nf::Int; T = Float64)

Return the outward unit normals at the facet nodes of the reference cube `[-1, 1]^3`.
"""
function normals_cube(nf::Int; T = Float64)
    dim = 3
    N = zeros(T, (dim, nf, 6)) # normal vector for each facet

    N[1, :, 1] .= -1.0
    N[1, :, 2] .= 1.0
    N[2, :, 3] .= -1.0
    N[2, :, 4] .= 1.0
    N[3, :, 5] .= -1.0
    N[3, :, 6] .= 1.0

    return N
end

"""
    facet_nodes_cube(n::Int)

Return the element node indices associated with each facet of a cube element with
`n` nodes.
"""
function facet_nodes_cube(n::Int)
    n1 = convert(Int, round(n^(1 / 3)))
    nf = convert(Int, round(n^(2 / 3)))
    facet_node_idx = zeros(Int, (6, nf))

    facet_node_idx[1, :] = 1:n1:n
    facet_node_idx[2, :] = n1:n1:n
    facet_node_idx[3, :] = collect(Iterators.flatten([1:n1...] .+ (i - 1) * nf
    for i in 1:n1))'
    facet_node_idx[4, :] = collect(Iterators.flatten([(nf + 1 - n1):nf...] .+ (i - 1) * nf
    for i in 1:n1))'
    facet_node_idx[5, :] = 1:nf
    facet_node_idx[6, :] = (n + 1 - nf):n

    return facet_node_idx
end

"""
    map_tensor_operators_to_tri(p::Int; operator_type::String = "lgl",
                                n1d::Int = -1, T = Float64)

Map tensor-product SBP operators to the quadrilateral subelements of the split
reference triangle.

Returns `(Hs, Qs, Ds, Es, Ns, Ss, dxs)`, the local norm, SBP, derivative,
boundary, normal, skew-symmetric, and metric data for each subelement.
"""
function map_tensor_operators_to_tri(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 2
    # Tensor-product nodes on the square
    xs, B = tensor_quad_nodes(p, operator_type = operator_type, n1d = n1d)
    n = size(xs, 2)
    nf = convert(Int, sqrt(n))
    quad_vert = get_quad_vert()
    Nhat = normals_square(convert(Int, sqrt(n)))
    facet_node_idx = facet_nodes_square(n)

    dxis = []
    dxs = []
    Js = []
    Ns = []
    for i in 1:3
        dxi = zeros(4, n)
        dx = zeros(4, n)
        J = zeros(1, n)
        for j in 1:n
            metric_tri!(
                xs[:, j], quad_vert[i], view(dxi, :, j), view(dx, :, j), view(J, :, j))
        end
        push!(dxis, dxi)
        push!(dxs, dx)
        push!(Js, J)
        N = zeros(T, (dim, nf, 4))
        for k in 1:4
            N[1, :, k] = J[facet_node_idx[k, :]] .*
                         (dx[1, facet_node_idx[k, :]] .* Nhat[1, :, k] .+
                          dx[3, facet_node_idx[k, :]] .* Nhat[2, :, k])
            N[2, :, k] = J[facet_node_idx[k, :]] .*
                         (dx[2, facet_node_idx[k, :]] .* Nhat[1, :, k] .+
                          dx[4, facet_node_idx[k, :]] .* Nhat[2, :, k])
        end
        push!(Ns, N)
    end

    Hhat, Qhat, Dhat, Ehat, Rhat = tensor_operators(
        p, dim, operator_type = operator_type, n1d = n1d, T = T)
    Es = []
    for k in 1:(dim + 1)
        E = zeros(T, (n, n, dim))
        for i in 1:dim
            for j in 1:4
                E[:, :, i] += Rhat[:, :, j]' * diagm(Ns[k][i, :, j] .* B) * Rhat[:, :, j]
            end
        end
        push!(Es, E)
    end

    Hs = []
    Qs = []
    Ds = []
    Ss = []
    for i in 1:(dim + 1)
        S = zeros(T, (n, n, dim))
        Q = zeros(T, (n, n, dim))
        E = Es[i]
        D = zeros(T, (n, n, dim))
        H = diagm(vec(Js[i])) * Hhat
        push!(Hs, H)
        S[:, :, 1] = 0.5 * (diagm(vec(Js[i]) .* dxs[i][1, :]) * Qhat[:, :, 1] +
                      diagm(vec(Js[i]) .* dxs[i][3, :]) * Qhat[:, :, 2]) -
                     0.5 * (Qhat[:, :, 1]' * diagm(vec(Js[i]) .* dxs[i][1, :]) +
                      Qhat[:, :, 2]' * diagm(vec(Js[i]) .* dxs[i][3, :]))
        S[:, :, 2] = 0.5 * (diagm(vec(Js[i]) .* dxs[i][2, :]) * Qhat[:, :, 1] +
                      diagm(vec(Js[i]) .* dxs[i][4, :]) * Qhat[:, :, 2]) -
                     0.5 * (Qhat[:, :, 1]' * diagm(vec(Js[i]) .* dxs[i][2, :]) +
                      Qhat[:, :, 2]' * diagm(vec(Js[i]) .* dxs[i][4, :]))
        push!(Ss, S)
        Q[:, :, 1] = S[:, :, 1] + 0.5 .* E[:, :, 1]
        Q[:, :, 2] = S[:, :, 2] + 0.5 .* E[:, :, 2]
        push!(Qs, Q)
        D[:, :, 1] = inv(H) * Q[:, :, 1]
        D[:, :, 2] = inv(H) * Q[:, :, 2]
        push!(Ds, D)
    end

    return Hs, Qs, Ds, Es, Ns, Ss, dxs
end
"""
    map_tensor_operators_to_tet(p::Int; operator_type::String = "lgl",
                                n1d::Int = -1, T = Float64)

Map tensor-product SBP operators to the hexahedral subelements of the split reference
tetrahedron.

Returns `(Hs, Qs, Ds, Es, Ns, dxs)`, the local norm, SBP, derivative, boundary,
normal, and metric data for each subelement.
"""
function map_tensor_operators_to_tet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 3
    # Tensor-product nodes on the cube
    xc, B = tensor_hex_nodes(p, operator_type = operator_type, n1d = n1d)
    n = size(xc, 2)
    n1 = round(n^(1 / 3))
    nf = convert(Int, round(n1^2))

    B = vec(kron(B, B))

    hex_vert = get_hex_vert()
    Nhat = normals_cube(nf)
    facet_node_idx = facet_nodes_cube(n)

    dxis = []
    dxs = []
    Js = []
    Ns = []
    for i in 1:4
        dxi = zeros(9, n)
        dx = zeros(9, n)
        J = zeros(1, n)
        N = zeros(3, n)
        for j in 1:n
            metric_tet!(
                xc[:, j], hex_vert[i], view(dxi, :, j), view(dx, :, j), view(J, :, j))
        end
        push!(dxis, dxi)
        push!(dxs, dx)
        push!(Js, J)

        N = zeros(T, (dim, nf, 2 * dim))
        for k in 1:6
            for id in 1:dim
                N[id, :, k] = J[facet_node_idx[k, :]] .*
                              (dx[id, facet_node_idx[k, :]] .* Nhat[1, :, k] .+
                               dx[dim + id, facet_node_idx[k, :]] .* Nhat[2, :, k] .+
                               dx[2 * dim + id, facet_node_idx[k, :]] .* Nhat[3, :, k])
            end
        end
        push!(Ns, N)
    end

    Hhat, Qhat, Dhat, Ehat, Rhat = tensor_operators(
        p, dim, operator_type = operator_type, n1d = n1d, T = T)
    Es = []
    for k in 1:(dim + 1)
        E = zeros(T, (n, n, dim))
        for i in 1:dim
            for j in 1:(2 * dim)
                E[:, :, i] += Rhat[:, :, j]' * diagm(Ns[k][i, :, j] .* B) * Rhat[:, :, j]
            end
        end
        push!(Es, E)
    end

    Hs = []
    Qs = []
    Ds = []
    for i in 1:(dim + 1)
        Q = zeros(T, (n, n, dim))
        E = Es[i]
        D = zeros(T, (n, n, dim))
        H = diagm(vec(Js[i])) * Hhat
        push!(Hs, H)
        Sx = 0.5 * (diagm(vec(Js[i]) .* dxs[i][1, :]) * Qhat[:, :, 1] +
              diagm(vec(Js[i]) .* dxs[i][1 + dim, :]) * Qhat[:, :, 2] +
              diagm(vec(Js[i]) .* dxs[i][1 + 2 * dim, :]) * Qhat[:, :, 3]) -
             0.5 * (Qhat[:, :, 1]' * diagm(vec(Js[i]) .* dxs[i][1, :]) +
              Qhat[:, :, 2]' * diagm(vec(Js[i]) .* dxs[i][1 + dim, :]) +
              Qhat[:, :, 3]' * diagm(vec(Js[i]) .* dxs[i][1 + 2 * dim, :]))
        Sy = 0.5 * (diagm(vec(Js[i]) .* dxs[i][2, :]) * Qhat[:, :, 1] +
              diagm(vec(Js[i]) .* dxs[i][2 + dim, :]) * Qhat[:, :, 2] +
              diagm(vec(Js[i]) .* dxs[i][2 + 2 * dim, :]) * Qhat[:, :, 3]) -
             0.5 * (Qhat[:, :, 1]' * diagm(vec(Js[i]) .* dxs[i][2, :]) +
              Qhat[:, :, 2]' * diagm(vec(Js[i]) .* dxs[i][2 + dim, :]) +
              Qhat[:, :, 3]' * diagm(vec(Js[i]) .* dxs[i][2 + 2 * dim, :]))
        Sz = 0.5 * (diagm(vec(Js[i]) .* dxs[i][3, :]) * Qhat[:, :, 1] +
              diagm(vec(Js[i]) .* dxs[i][3 + dim, :]) * Qhat[:, :, 2] +
              diagm(vec(Js[i]) .* dxs[i][3 + 2 * dim, :]) * Qhat[:, :, 3]) -
             0.5 * (Qhat[:, :, 1]' * diagm(vec(Js[i]) .* dxs[i][3, :]) +
              Qhat[:, :, 2]' * diagm(vec(Js[i]) .* dxs[i][3 + dim, :]) +
              Qhat[:, :, 3]' * diagm(vec(Js[i]) .* dxs[i][3 + 2 * dim, :]))

        Q[:, :, 1] = Sx + 0.5 .* E[:, :, 1]
        Q[:, :, 2] = Sy + 0.5 .* E[:, :, 2]
        Q[:, :, 3] = Sz + 0.5 .* E[:, :, 3]
        push!(Qs, Q)
        D[:, :, 1] = inv(H) * Q[:, :, 1]
        D[:, :, 2] = inv(H) * Q[:, :, 2]
        D[:, :, 3] = inv(H) * Q[:, :, 3]
        push!(Ds, D)
    end

    return Hs, Qs, Ds, Es, Ns, dxs
end

"""
    global_node_index_tri(p::Int; operator_type::String = "lgl",
                          n1d::Int = -1, T = Float64)

Return the global node coordinates and local-to-global node maps for the split
triangle.
"""
function global_node_index_tri(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    xs, _ = tensor_quad_nodes(p, operator_type = operator_type, n1d = n1d)
    xt = square_to_tri_map(xs)
    n = size(xs, 2)

    facet_node_idx = facet_nodes_square(n)
    xg = copy(xt)
    remove_idx = collect(Iterators.flatten([
        n .+ facet_node_idx[1, :], (2 * n) .+ facet_node_idx[2, :],
        (2 * n) .+ facet_node_idx[3, :]]))
    xg = xg[:, filter(x -> !(x in remove_idx), 1:size(xg, 2))]

    loc_glob_idx = []
    for k in 1:3
        x = zeros(Int, (2, n))
        x[1, :] = 1:n
        for i in 1:n
            xgidx = xg .- xt[:, (k - 1) * n + i]
            col_norm = [norm(xgidx[:, j]) for j in 1:size(xg, 2)]
            ig = argmin(col_norm)
            x[2, i] = ig
        end
        push!(loc_glob_idx, x)
    end
    return xg, loc_glob_idx
end

"""
    global_node_index_tet(p::Int; operator_type::String = "lgl",
                          n1d::Int = -1, T = Float64)

Return the global node coordinates and local-to-global node maps for the split
tetrahedron.
"""
function global_node_index_tet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    xh, _ = tensor_hex_nodes(p, operator_type = operator_type, n1d = n1d)
    xt = cube_to_tet_map(xh)
    n = size(xh, 2)

    facet_node_idx = facet_nodes_cube(n)
    xg = copy(xt)
    remove_idx = collect(Iterators.flatten([n .+ facet_node_idx[1, :],
        (2 * n) .+ facet_node_idx[2, :],
        (2 * n) .+ facet_node_idx[3, :],
        (3 * n) .+ facet_node_idx[1, :],
        (3 * n) .+ facet_node_idx[4, :],
        (3 * n) .+ facet_node_idx[6, :]]))
    xg = xg[:, filter(x -> !(x in remove_idx), 1:size(xg, 2))]

    loc_glob_idx = []
    for k in 1:4
        x = zeros(Int, (2, n))
        x[1, :] = 1:n
        for i in 1:n
            xgidx = xg .- xt[:, (k - 1) * n + i]
            col_norm = [norm(xgidx[:, j]) for j in 1:size(xg, 2)]
            ig = argmin(col_norm)
            x[2, i] = ig
        end
        push!(loc_glob_idx, x)
    end
    return xg, loc_glob_idx
end

"""
    construct_zmatrix(glob_idx::Array{T}, i::Int, j::Int, nglob::Int) where {T}

Construct the sparse scatter matrix used to patch split subelements in continuous
Galerkin form.

# References
- J. E. Hicken, D. C. Del Rey Fernandez, D. W. Zingg (2016)
  Multidimensional summation-by-parts operators: General theory and application to
  simplex elements.
  [DOI: 10.1137/15M1038360](https://doi.org/10.1137/15M1038360)
"""
function construct_zmatrix(glob_idx::Array{T}, i::Int, j::Int, nglob::Int) where {T}
    ihat = glob_idx[2, i]
    jhat = glob_idx[2, j]
    ei = sparse(I, nglob, nglob)[:, ihat]
    ej = sparse(I, nglob, nglob)[:, jhat]
    Z = ei * ej'
    return Z
end

"""
    construct_pmatrix(np::Int, nd::Int, l::Int, p::Int;
                      operator_type::String = "lgl", n1d::Int = -1)

Construct the local-to-global projection matrix for subdomain `l` of a split
triangle.
"""
function construct_pmatrix(np::Int, nd::Int, l::Int, p::Int;
        operator_type::String = "lgl", n1d::Int = -1)
    ~, loc_glob_idx = global_node_index_tri(p, operator_type = operator_type, n1d = n1d)
    map = loc_glob_idx[l]
    P = zeros(np, nd)
    for i in 1:nd
        e = zeros(np, 1)
        ihat = map[2, i]
        e[ihat] = 1
        P[:, i] = e
    end
    return P
end

"""
    construct_split_operator_tri(p::Int; operator_type::String = "lgl",
                                 n1d::Int = -1, T = Float64)

Construct patched TSS-SBP volume operators on the reference triangle.

Returns `(H, Q, D, E, S)`, where `H` is the norm matrix and `Q`, `D`, `E`, and
`S` are vectors of coordinate-direction matrices.
"""
function construct_split_operator_tri(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    Hs, Qs, Ds, Es, _, Ss = map_tensor_operators_to_tri(
        p, operator_type = operator_type, n1d = n1d)
    xg, loc_glob_idx = global_node_index_tri(p, operator_type = operator_type, n1d = n1d)
    n = size(Hs[1], 1)
    nglob = size(xg, 2)
    dim = 2

    H = spzeros(nglob, nglob)
    S = [spzeros(nglob, nglob), spzeros(nglob, nglob)]
    Q = [spzeros(nglob, nglob), spzeros(nglob, nglob)]
    D = [spzeros(nglob, nglob), spzeros(nglob, nglob)]
    E = [spzeros(nglob, nglob), spzeros(nglob, nglob)]
    for k in 1:(dim + 1)
        for i in 1:n
            for j in 1:n
                glob_idx = loc_glob_idx[k]
                Z = construct_zmatrix(glob_idx, i, j, nglob)
                if Hs[k][i, j] != 0.0
                    H[:, :] += (Hs[k][i, j] * Z)
                end
                for id in 1:dim
                    if Ss[k][i, j, id] != 0.0
                        S[id] += (Ss[k][i, j, id] * Z)
                    end
                    if Qs[k][i, j, id] != 0.0
                        Q[id] += (Qs[k][i, j, id] * Z)
                    end
                    if Es[k][i, j, id] != 0.0
                        E[id] += (Es[k][i, j, id] * Z)
                    end
                end
            end
        end
    end

    for id in 1:dim
        D[id] = inv(Matrix(H)) * Q[id]
    end
    S = [Matrix(m) for m in S]
    Q = [Matrix(m) for m in Q]
    D = [Matrix(m) for m in D]
    E = [Matrix(m) for m in E]
    return Matrix(H), Q, D, E, S
end

"""
    construct_split_operator_tet(p::Int; operator_type::String = "lgl",
                                 n1d::Int = -1, T = Float64)

Construct patched TSS-SBP volume operators on the reference tetrahedron.

Returns `(H, Q, D, E)`, where `H` is the norm matrix and `Q`, `D`, and `E` are
vectors of coordinate-direction matrices.
"""
function construct_split_operator_tet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    Hs, Qs, Ds, Es, _ = map_tensor_operators_to_tet(
        p, operator_type = operator_type, n1d = n1d)
    xg, loc_glob_idx = global_node_index_tet(p, operator_type = operator_type, n1d = n1d)
    n = size(Hs[1], 1)
    nglob = size(xg, 2)
    dim = 3

    H = spzeros(nglob, nglob)
    Q = [spzeros(nglob, nglob), spzeros(nglob, nglob), spzeros(nglob, nglob)]
    D = [spzeros(nglob, nglob), spzeros(nglob, nglob), spzeros(nglob, nglob)]
    E = [spzeros(nglob, nglob), spzeros(nglob, nglob), spzeros(nglob, nglob)]
    for k in 1:(dim + 1)
        for i in 1:n
            for j in 1:n
                glob_idx = loc_glob_idx[k]
                Z = construct_zmatrix(glob_idx, i, j, nglob)
                if Hs[k][i, j] != 0.0
                    H[:, :] += (Hs[k][i, j] * Z)
                end
                for id in 1:dim
                    if Qs[k][i, j, id] != 0.0
                        Q[id] += (Qs[k][i, j, id] * Z)
                    end
                    if Es[k][i, j, id] != 0.0
                        E[id] += (Es[k][i, j, id] * Z)
                    end
                end
            end
        end
    end

    for id in 1:dim
        D[id] = inv(Matrix(H)) * Q[id]
    end
    Q = [Matrix(m) for m in Q]
    D = [Matrix(m) for m in D]
    E = [Matrix(m) for m in E]
    return Matrix(H), Q, D, E
end

"""
    global_node_index_tri_facet(p::Int; operator_type::String = "lgl",
                                n1d::Int = -1, T = Float64)

Return facet node coordinates and local-to-global facet maps for the split triangle.
"""
function global_node_index_tri_facet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 2
    xs, _ = tensor_quad_nodes(p, operator_type = operator_type, n1d = n1d)
    xt = square_to_tri_map(xs)
    xg, _ = global_node_index_tri(p, operator_type = operator_type, n1d = n1d)
    n = size(xs, 2)
    n1 = convert(Int, round(n^(1 / dim)))
    nf = n1^(dim - 1)

    facet_node_idx = facet_nodes_square(n)
    xf = zeros(T, (dim, dim * nf - 1, dim + 1))
    keep_idx = []
    push!(keep_idx,
        collect(Iterators.flatten([(n) .+ facet_node_idx[2, :],
            reverse((2 * n) .+ facet_node_idx[4, 1:(end - 1)])])))
    push!(keep_idx,
        collect(Iterators.flatten([reverse((2 * n) .+ facet_node_idx[1, :]),
            reverse(facet_node_idx[1, 1:(end - 1)])])))
    push!(keep_idx,
        collect(Iterators.flatten([facet_node_idx[3, :], (n) .+ facet_node_idx[3, 2:end]])))
    for k in 1:(dim + 1)
        xf[:, :, k] = xt[:, keep_idx[k]]
    end
    xfall = zeros(T, (dim, nf, dim * (dim + 1)))
    xfall[:, :, 1] = xt[:, (n) .+ facet_node_idx[2, :]]
    xfall[:, :, 2] = xt[:, ((2 * n) .+ facet_node_idx[4, :])]
    xfall[:, :, 3] = xt[:, ((2 * n) .+ facet_node_idx[1, :])]
    xfall[:, :, 4] = xt[:, (facet_node_idx[1, :])]
    xfall[:, :, 5] = xt[:, facet_node_idx[3, :]]
    xfall[:, :, 6] = xt[:, (n) .+ facet_node_idx[3, :]]

    loc_glob_facet_idx = []
    for k in 1:(dim * (dim + 1))
        x = zeros(Int, (3, nf))
        x[1, :] = 1:nf
        for i in 1:nf
            xfidx = xf[:, :, convert(Int, ceil(k / dim))] .- xfall[:, i, k]
            col_norm = [norm(xfidx[:, j]) for j in 1:size(xf, 2)]
            ig = argmin(col_norm)
            x[2, i] = ig
        end
        for i in 1:nf
            xgidx = xg .- xfall[:, i, k]
            col_norm = [norm(xgidx[:, j]) for j in 1:size(xg, 2)]
            ig = argmin(col_norm)
            x[3, i] = ig
        end
        push!(loc_glob_facet_idx, x)
    end
    return xf, loc_glob_facet_idx
end

"""
    construct_split_facet_operator_tri(p::Int; operator_type::String = "lgl",
                                       n1d::Int = -1, T = Float64)

Construct patched TSS-SBP facet operators on the reference triangle.

Returns `(B, N, R, E)`, where `B` contains facet quadrature weights, `N` contains
scaled normals, `R` extrapolates volume values to facets, and `E` contains the
boundary integration matrices.
"""
function construct_split_facet_operator_tri(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 2
    _, Bhat = tensor_quad_nodes(p, operator_type = operator_type, n1d = n1d)

    _, _, _, _, Nhat, _ = map_tensor_operators_to_tri(
        p, operator_type = operator_type, n1d = n1d)
    nf = length(Bhat)
    n = (dim + 1) * nf^dim - (dim + dim^(dim - 2)) * nf^(dim - 1) +
        (dim - 2) * ((dim + 1) * nf - 2) + 1

    xf, loc_glob_idx = global_node_index_tri_facet(
        p, operator_type = operator_type, n1d = n1d)
    nglob = size(xf, 2)
    B = zeros(T, (nglob, nglob, dim + 1))
    for k in 1:(dim + 1)
        for i in 1:dim
            glob_idx = loc_glob_idx[(k - 1) * dim + i]
            for j in 1:nf
                Z = construct_zmatrix(glob_idx, j, j, nglob)
                B[:, :, k] += (Bhat[j] * Z)
            end
        end
    end

    N_idx = [[2 2; 3 4], [3 1; 1 1], [1 3; 2 3]]
    N = zeros(T, (dim, nglob, dim + 1))
    for id in 1:dim
        for k in 1:(dim + 1)
            jj = dim * (k - 1)
            idx_vec = (collect(Iterators.flatten([
                loc_glob_idx[jj + 1][2, :], loc_glob_idx[jj + 2][2, :]])))
            idx = [findfirst(isequal(num), idx_vec) for num in 1:nglob]
            N[id, :, k] = collect(Iterators.flatten([
                Nhat[N_idx[k][1, 1]][id, :, N_idx[k][1, 2]],
                Nhat[N_idx[k][2, 1]][id, :, N_idx[k][2, 2]]]))[idx]
        end
    end

    R = zeros(T, (nglob, n, dim + 1))
    for k in 1:(dim + 1)
        jj = dim * (k - 1)
        loc_idx = unique(collect(Iterators.flatten([
            loc_glob_idx[jj + 1][2, :], loc_glob_idx[jj + 2][2, :]])))
        glob_idx = unique(collect(Iterators.flatten([
            loc_glob_idx[jj + 1][3, :], loc_glob_idx[jj + 2][3, :]])))
        for i in 1:nglob
            R[loc_idx[i], glob_idx[i], k] = 1.0
        end
    end

    E = zeros(T, (n, n, dim))
    for i in 1:dim
        for k in 1:(dim + 1)
            E[:, :, i] += R[:, :, k]' * diagm(N[i, :, k]) * B[:, :, k] * R[:, :, k]
        end
    end
    return B, N, R, E
end

"""
    global_node_index_tet_facet(p::Int; operator_type::String = "lgl",
                                n1d::Int = -1, T = Float64)

Return facet node coordinates and local-to-global facet maps for the split tetrahedron.
"""
function global_node_index_tet_facet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 3
    xh, _ = tensor_hex_nodes(p, operator_type = operator_type, n1d = n1d)
    xt = cube_to_tet_map(xh)
    xg, _ = global_node_index_tet(p, operator_type = operator_type, n1d = n1d)
    n = size(xh, 2)
    n1 = convert(Int, round(n^(1 / dim)))
    nf = n1^(dim - 1)

    facet_node_idx = facet_nodes_cube(n)
    xf = zeros(T, (dim, dim * nf - 3 * n1 + 1, dim + 1))
    keep_idx = []
    push!(keep_idx,
        collect(Iterators.flatten([facet_node_idx[3, :],
            (n .+ facet_node_idx[3, :]),
            ((3 * n) .+ facet_node_idx[5, :])])))
    push!(keep_idx,
        collect(Iterators.flatten([(n .+ facet_node_idx[2, :]),
            (2 * n) .+ collect(Iterators.flatten([reverse(facet_node_idx[4, :][i:min(
                                           i + n1 - 1, end)])
                                       for i in 1:n1:length(facet_node_idx[4, :])])),
            (3 * n) .+ collect(Iterators.flatten([reverse(facet_node_idx[2, :][i:min(
                                           i + n1 - 1, end)])
                                       for i in 1:n1:length(facet_node_idx[2, :])]))])))
    push!(keep_idx,
        collect(Iterators.flatten([(facet_node_idx[1, :]),
            (2 * n) .+ (facet_node_idx[1, :]),
            (3 * n) .+ (facet_node_idx[3, :])])))
    push!(keep_idx,
        collect(Iterators.flatten([(facet_node_idx[5, :]),
            (n) .+ (facet_node_idx[5, :]),
            (2 * n) .+ reverse(facet_node_idx[5, :])])))

    unique_idx = [[keep_idx[1][1]], [keep_idx[2][1]], [keep_idx[3][1]], [keep_idx[4][1]]]
    for k in 1:(dim + 1)
        facet_nodes = xt[:, keep_idx[k]]
        for i in 2:(nf * dim)
            shifted_facet_nodes = facet_nodes .- facet_nodes[:, i]
            col_norm = [norm(shifted_facet_nodes[:, j]) for j in 1:size(facet_nodes, 2)]
            idx = argmin(col_norm[1:(i - 1)])
            if norm(shifted_facet_nodes[:, idx]) > 1e-14
                push!(unique_idx[k], keep_idx[k][i])
            end
        end
    end

    for k in 1:(dim + 1)
        xf[:, :, k] = xt[:, unique_idx[k]]
    end
    xfall = zeros(T, (dim, nf, dim * (dim + 1)))
    xfall[:, :, 1] = xt[:, facet_node_idx[3, :]]
    xfall[:, :, 2] = xt[:, (n .+ facet_node_idx[3, :])]
    xfall[:, :, 3] = xt[:, ((3 * n) .+ facet_node_idx[5, :])]
    xfall[:, :, 4] = xt[:, (n .+ facet_node_idx[2, :])]
    xfall[:, :, 5] = xt[:, (2 * n) .+ (facet_node_idx[4, :])]
    xfall[:, :, 6] = xt[:, (3 * n) .+ (facet_node_idx[2, :])]
    xfall[:, :, 7] = xt[:, (facet_node_idx[1, :])]
    xfall[:, :, 8] = xt[:, (2 * n) .+ (facet_node_idx[1, :])]
    xfall[:, :, 9] = xt[:, (3 * n) .+ (facet_node_idx[3, :])]
    xfall[:, :, 10] = xt[:, (facet_node_idx[5, :])]
    xfall[:, :, 11] = xt[:, (n) .+ (facet_node_idx[5, :])]
    xfall[:, :, 12] = xt[:, (2 * n) .+ (facet_node_idx[5, :])]

    loc_glob_facet_idx = []
    for k in 1:(dim * (dim + 1))
        x = zeros(Int, (3, nf))
        x[1, :] = 1:nf
        for i in 1:nf
            xfidx = xf[:, :, convert(Int, ceil(k / dim))] .- xfall[:, i, k]
            col_norm = [norm(xfidx[:, j]) for j in 1:size(xf, 2)]
            ig = argmin(col_norm)
            x[2, i] = ig
        end
        for i in 1:nf
            xgidx = xg .- xfall[:, i, k]
            col_norm = [norm(xgidx[:, j]) for j in 1:size(xg, 2)]
            ig = argmin(col_norm)
            x[3, i] = ig
        end
        push!(loc_glob_facet_idx, x)
    end
    return xf, loc_glob_facet_idx
end

"""
    construct_split_facet_operator_tet(p::Int; operator_type::String = "lgl",
                                       n1d::Int = -1, T = Float64)

Construct patched TSS-SBP facet operators on the reference tetrahedron.

Returns `(B, N, R, E)`, where `B` contains facet quadrature weights, `N` contains
scaled normals, `R` extrapolates volume values to facets, and `E` contains the
boundary integration matrices.
"""
function construct_split_facet_operator_tet(
        p::Int; operator_type::String = "lgl", n1d::Int = -1, T = Float64)
    dim = 3
    _, B1 = tensor_quad_nodes(p, operator_type = operator_type, n1d = n1d)

    Bhat = kron(diagm(B1), diagm(B1))
    _, _, _, _, Nhat = map_tensor_operators_to_tet(
        p, operator_type = operator_type, n1d = n1d)
    n1 = length(B1)
    nf = n1^(dim - 1)
    n = (dim + 1) * n1^dim - (dim + dim^(dim - 2)) * n1^(dim - 1) +
        (dim - 2) * ((dim + 1) * n1 - 2) + 1
    N_idx = [[1 3; 2 3; 4 5], [2 2; 3 4; 4 2], [1 1; 3 1; 4 3], [1 5; 2 5; 3 5]]

    xf, loc_glob_idx = global_node_index_tet_facet(
        p, operator_type = operator_type, n1d = n1d)
    nglob = size(xf, 2)
    B = zeros(T, (nglob, nglob, dim + 1))
    N = zeros(T, (dim, nglob, dim + 1))
    for k in 1:(dim + 1)
        for i in 1:dim
            glob_idx = loc_glob_idx[(k - 1) * dim + i]
            for j in 1:nf
                Z = construct_zmatrix(glob_idx, j, j, nglob)
                B[:, :, k] += (Bhat[j, j] * Z)
            end
        end
    end

    for id in 1:dim
        for k in 1:(dim + 1)
            jj = dim * (k - 1)
            idx_vec = (collect(Iterators.flatten([
                loc_glob_idx[jj + 1][2, :], loc_glob_idx[jj + 2][2, :],
                loc_glob_idx[jj + 3][2, :]])))
            idx = [findfirst(isequal(num), idx_vec) for num in 1:nglob]
            N[id, :, k] = collect(Iterators.flatten([
                Nhat[N_idx[k][1, 1]][id, :, N_idx[k][1, 2]],
                Nhat[N_idx[k][2, 1]][id, :, N_idx[k][2, 2]],
                Nhat[N_idx[k][3, 1]][id, :, N_idx[k][3, 2]]]))[idx]
        end
    end

    R = zeros(T, (nglob, n, dim + 1))
    for k in 1:(dim + 1)
        jj = dim * (k - 1)
        loc_idx = unique(collect(Iterators.flatten([
            loc_glob_idx[jj + 1][2, :], loc_glob_idx[jj + 2][2, :],
            loc_glob_idx[jj + 3][2, :]])))
        glob_idx = unique(collect(Iterators.flatten([
            loc_glob_idx[jj + 1][3, :], loc_glob_idx[jj + 2][3, :],
            loc_glob_idx[jj + 3][3, :]])))
        for i in 1:nglob
            R[loc_idx[i], glob_idx[i], k] = 1.0
        end
    end

    E = zeros(T, (n, n, dim))
    for i in 1:dim
        for k in 1:(dim + 1)
            E[:, :, i] += R[:, :, k]' * diagm(N[i, :, k]) * B[:, :, k] * R[:, :, k]
        end
    end
    return B, N, R, E
end
